#include <iostream>
using namespace std;
int main() {
 int a;
 int b;
 int c;
 cin >> a;
 b = 5000;
 c = a / b;
 cout << "Total number of notes:" << endl;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 1000;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 500;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 100;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 50;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 20;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 10;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 5;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 2;
 c = a / b;
 cout << b << " : " << c << endl;
 a = a - (b * c);
 b = 1;
 c = a / b;
 cout << b << " : " << c << endl;
 return 0;
}
